"""Setup reusable modifier groups with many-to-many relationship

Revision ID: 163fe43f658d
Revises: eebbfad4e1cc
Create Date: 2025-04-29 14:07:46.336137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163fe43f658d'
down_revision = 'eebbfad4e1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_modifier_groups',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('modifier_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'modifier_group_id')
    )
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_modifier_groups_dish_id')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('modifier_groups_dish_id_fkey', type_='foreignkey')
        batch_op.drop_column('dish_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('modifier_groups_dish_id_fkey', 'dishes', ['dish_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_modifier_groups_dish_id', ['dish_id'], unique=False)

    op.drop_table('dish_modifier_groups')
    # ### end Alembic commands ###
