"""Додана таблиця OTP до бази даних

Revision ID: 4594164b6f2e
Revises: 25caf197d36b
Create Date: 2025-05-06 17:32:24.477087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4594164b6f2e'
down_revision = '25caf197d36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_otps_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_otps_phone_number'))

    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###
