"""Додав час початку та кінця резервації

Revision ID: 6dd9b5d7b6b9
Revises: 4594164b6f2e
Create Date: 2025-05-08 14:01:51.427897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dd9b5d7b6b9'
down_revision = '4594164b6f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('reservation_end_time', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reservations_reservation_end_time'), ['reservation_end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_reservation_start_time'), ['reservation_start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_reservation_start_time'))
        batch_op.drop_index(batch_op.f('ix_reservations_reservation_end_time'))
        batch_op.drop_column('reservation_end_time')
        batch_op.drop_column('reservation_start_time')

    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
