"""Added modifier groups to dishes that change price based on selected one

Revision ID: eebbfad4e1cc
Revises: e817c9fc0e49
Create Date: 2025-04-29 12:49:29.212669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebbfad4e1cc'
down_revision = 'e817c9fc0e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modifier_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('selection_type', sa.Enum('single', 'multiple', name='selection_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modifier_groups_dish_id'), ['dish_id'], unique=False)

    op.create_table('modifier_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_modifier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modifier_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modifier_options_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modifier_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modifier_options_group_id'))

    op.drop_table('modifier_options')
    with op.batch_alter_table('modifier_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modifier_groups_dish_id'))

    op.drop_table('modifier_groups')
    # ### end Alembic commands ###
